# Check `config.schema.json` for the complete schema.
system:
  demo: false
  account:
    demo: DU0000000
    actual: U0000000
  suppress-warning: true

bot:
  strategy-check-interval-sec: 0.15
  position-fetch-interval-sec: 10
  line:
    enable: true
    token: <TOKEN>
    px-auto-report:
      interval-sec: 3
      symbols:
        - MNQ@300

data:
  trend-window:
    300: 96
    3600: 24
  diff-sma-window:
    default: 20
    300: 5
    3600: 20
  sma:
    - 5
    - 10
    - 22
    - 66
    - 128
    - 256
  execution-period-sec:
    default: 60
    MNQ: 300

sr-level:
  multiplier: 1.5
  strong-threshold: 0.7
  custom:
    # MNQM2
    477837024:
      - level: 15347.25
      - level: 15221.25
        strong: true
      - level: 15051.75
        strong: true
      - level: 14844.25
      - level: 14763.5
      - level: 14632.75
        strong: true
      - level: 14535
      - level: 14469.25
      - level: 14388
      - level: 14249.75
        strong: true

risk-management:
  take-profit-x: 15
  stop-loss-x: 3
  pnl-warning:
    px-diff-val: 50
    px-diff-sma-ratio: 2
    total-pnl: 2000
    unrealized-pnl: 350

server:
  client-id:
    demo: 1
    live: 99
  position-on-first-realized:
    # MNQH2
    461318792: 1
    # MYM MAR 22
    477836934: 0
  contract:
    - symbol: MNQH2
      exchange: GLOBEX
      type: Futures
      data:
      - duration: 86400 S
        bar-size: 1 min
        period-secs: 60
      - duration: 86400 S
        bar-size: 5 mins
        period-secs: 300
        is-major: true
      - duration: 10 D
        bar-size: 1 hour
        period-secs: 3600
      - duration: 30 D
        bar-size: 1 day
        period-secs: 86400
    - symbol: MYM  JUN 22
      exchange: ECBOT
      type: Futures
      enable: false
      data:
      - duration: 86400 S
        bar-size: 1 min
        period-secs: 60
      - duration: 86400 S
        bar-size: 5 mins
        period-secs: 300
    - symbol: SPX
      exchange: CBOE
      type: Index
      data:
      - duration: 360 D
        bar-size: 1 day
        period-secs: 86400
    - symbol: INDU
      exchange: CME
      type: Index
      data:
      - duration: 360 D
        bar-size: 1 day
        period-secs: 86400
