system:
  demo: false
  account:
    demo: <ACCOUNT_NUMBER>
    actual: <ACCOUNT_NUMBER>

bot:
  strategy-check-interval-sec: 0.15
  position-fetch-interval-sec: 10

data:
  # Only used by bot (spread) - needs to run `run_server_info` first
  market: ws://localhost:8000
  # Count of bar to lookback for calculating the current trend
  # > Key = period sec, must match with `server.contract[].data[].period-secs`
  # > Value = count of bar to lookback
  # -----------------
  # `300: 96` means to lookback 96 bars (8 hrs) on data of period in 300s
  trend-window:
    300: 96
    3600: 24
  # Period of diff SMA
  # > Key = period sec, or `default`
  # > Value = SMA period
  # -----------------
  # `300: 5` means to use 5 SMA on data of period in 300s
  diff-sma-window:
    default: 20
    300: 5
    3600: 20

sr-level:
  # Determines the gap between each level, the larger the multiplier, the larger the gap
  # > Used together with the average of all diff SMA to get the minimum gap between SR levels
  multiplier: 1.5
  # Threshold to determine that an S/R level is "strong" in terms of its relative strength (0~1)
  strong-threshold: 0.7

risk-management:
  take-profit-x: 15
  stop-loss-x: 3

server:
  client-id:
    demo: 1
    live: 99
  position-on-first-realized:
    # MNQH2
    461318792: 1
    # MYM MAR 22
    477836934: 0
  contract:
    - symbol: MNQH2
      exchange: GLOBEX
      data:
      - duration: 86400 S
        bar-size: 1 min
        period-secs: 60
      - duration: 86400 S
        bar-size: 5 mins
        period-secs: 300
        is-major: true  # Indicates that the data is the main focus, defaults to `false`
      - duration: 10 D
        bar-size: 1 hours
        period-secs: 3600
      - duration: 30 D
        bar-size: 1 day
        period-secs: 86400
    - symbol: MYM  MAR 22
      exchange: ECBOT
      data:
      - duration: 86400 S
        bar-size: 1 min
        period-secs: 60
      - duration: 86400 S
        bar-size: 5 mins
        period-secs: 300
