system:
  demo: false
  account:
    demo: <ACCOUNT_NUMBER>
    actual: <ACCOUNT_NUMBER>

bot:
  strategy-check-interval-sec: 0.075
  position-fetch-interval-sec: 3

data:
  # Only used by bot (spread) - needs to run `run_server_info` first
  market: ws://localhost:8000

support-resistance:
  period: 60
  multiplier: 1.2

risk-management:
  take-profit-ampl: 3.5
  stop-loss-ampl: 1.7
